# Generated by Django 2.1.1 on 2020-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile-pics/default.jpg', upload_to='profile-pics'),
        ),
    ]
