# Generated by Django 3.0.7 on 2020-07-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Meriden', 'Meriden'), ('North Haven', 'North Haven')], max_length=50)),
                ('summary', models.TextField(max_length=300)),
                ('type', models.CharField(choices=[('Website', 'Website'), ('IT Issue', 'IT Issue'), ('HR Issue', 'HR Issue'), ('Password Help', 'Password Help'), ('Purchase', 'Purchase'), ('Mobile', 'Mobile'), ('Network', 'Network'), ('Security', 'Security'), ('Email', 'Email')], max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('Assigned', 'Assigned'), ('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Canceled', 'Canceled'), ('Resolved', 'Resolved')], max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.TicketGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTicketGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ticket group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Meriden', 'Meriden'), ('North Haven', 'North Haven')], max_length=50)),
                ('summary', models.TextField(max_length=300)),
                ('type', models.CharField(choices=[('Website', 'Website'), ('IT Issue', 'IT Issue'), ('HR Issue', 'HR Issue'), ('Password Help', 'Password Help'), ('Purchase', 'Purchase'), ('Mobile', 'Mobile'), ('Network', 'Network'), ('Security', 'Security'), ('Email', 'Email')], max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('Assigned', 'Assigned'), ('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Canceled', 'Canceled'), ('Resolved', 'Resolved')], max_length=100)),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracker.TicketGroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ticket',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
