# Generated by Django 3.0.4 on 2020-03-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200316_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='current_date',
        ),
    ]
