# Generated by Django 2.1.1 on 2020-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200317_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
