# Generated by Django 3.0.4 on 2020-03-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_num', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_date', models.DateTimeField()),
                ('submitter', models.CharField(max_length=100)),
            ],
        ),
    ]
