# Generated by Django 3.0.4 on 2020-03-16 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_ticket_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_status',
            field=models.CharField(choices=[('1', 'Assigned'), ('2', 'Open'), ('3', 'Pending'), ('4', 'Closed')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
