# Generated by Django 2.1.1 on 2020-03-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200318_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='current_status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=10),
        ),
    ]
