# Generated by Django 2.1.1 on 2020-03-19 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20200319_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
